### ISSUE TITLE
Feature Request: 5120x1440 wallpapers for ultra-wide displays

### ISSUE THREAD

**Issue by riverar** [microsoft/Build2020_DigitalSwag#1]
Requesting wallpapers for 5120x1440 (32:9) to fit this display:

![image](https://user-images.githubusercontent.com/475132/82266916-daac9200-991f-11ea-9cc1-0c714d0724f1.png)

**Comment by livelovegeek** [comment]
I'm looking into this for you!

**Comment by livelovegeek** [comment]
Three ultrawide versions have been added to the repo: https://github.com/microsoft/Build2020_DigitalSwag/tree/master/Desktop%20Wallpapers%20-%20Build%202020
